-- MySQL Script generated by MySQL Workbench
-- Sun Jun  7 19:59:54 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema siroma_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `siroma_db` ;

-- -----------------------------------------------------
-- Schema siroma_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siroma_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `siroma_db` ;

-- -----------------------------------------------------
-- Table `siroma_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siroma_db`.`users` ;

CREATE TABLE IF NOT EXISTS `siroma_db`.`users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `student_number` VARCHAR(20) NOT NULL,
  `full_name` VARCHAR(120) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `faculty` VARCHAR(100) NULL DEFAULT NULL,
  `study_program` VARCHAR(100) NULL DEFAULT NULL,
  `entry_year` YEAR NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_users_student_number` (`student_number` ASC) VISIBLE,
  UNIQUE INDEX `uq_users_email` (`email` ASC) VISIBLE,
  INDEX `idx_users_full_name` (`full_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `siroma_db`.`organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siroma_db`.`organizations` ;

CREATE TABLE IF NOT EXISTS `siroma_db`.`organizations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_code` VARCHAR(20) NOT NULL,
  `organization_name` VARCHAR(120) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `contact_email` VARCHAR(150) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_organizations_code` (`organization_code` ASC) VISIBLE,
  UNIQUE INDEX `uq_organizations_name` (`organization_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `siroma_db`.`recruitment_periods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siroma_db`.`recruitment_periods` ;

CREATE TABLE IF NOT EXISTS `siroma_db`.`recruitment_periods` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT UNSIGNED NOT NULL,
  `created_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `recruitment_title` VARCHAR(150) NOT NULL,
  `academic_year` VARCHAR(9) NOT NULL,
  `registration_start_date` DATE NOT NULL,
  `registration_end_date` DATE NOT NULL,
  `total_quota` INT UNSIGNED NOT NULL DEFAULT '1',
  `recruitment_status` ENUM('draft', 'open', 'closed', 'completed') NOT NULL DEFAULT 'draft',
  `description` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_recruitment_periods_creator` (`created_by` ASC) VISIBLE,
  INDEX `idx_recruitment_periods_org_status_dates` (`organization_id` ASC, `recruitment_status` ASC, `registration_start_date` ASC, `registration_end_date` ASC) VISIBLE,
  CONSTRAINT `fk_recruitment_periods_creator`
    FOREIGN KEY (`created_by`)
    REFERENCES `siroma_db`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recruitment_periods_organization`
    FOREIGN KEY (`organization_id`)
    REFERENCES `siroma_db`.`organizations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `siroma_db`.`applications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siroma_db`.`applications` ;

CREATE TABLE IF NOT EXISTS `siroma_db`.`applications` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `application_code` VARCHAR(30) NOT NULL DEFAULT '',
  `recruitment_period_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `motivation` TEXT NOT NULL,
  `final_score` DECIMAL(5,2) NULL DEFAULT NULL,
  `application_status` ENUM('submitted', 'under_review', 'accepted', 'rejected', 'withdrawn') NOT NULL DEFAULT 'submitted',
  `reviewer_notes` VARCHAR(500) NULL DEFAULT NULL,
  `submitted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reviewed_at` DATETIME NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_applications_code` (`application_code` ASC) VISIBLE,
  UNIQUE INDEX `uq_applications_recruitment_user` (`recruitment_period_id` ASC, `user_id` ASC) VISIBLE,
  INDEX `fk_applications_user` (`user_id` ASC) VISIBLE,
  INDEX `idx_applications_recruitment_status_date` (`recruitment_period_id` ASC, `application_status` ASC, `submitted_at` ASC) VISIBLE,
  CONSTRAINT `fk_applications_recruitment`
    FOREIGN KEY (`recruitment_period_id`)
    REFERENCES `siroma_db`.`recruitment_periods` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_applications_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `siroma_db`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `siroma_db`.`application_documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siroma_db`.`application_documents` ;

CREATE TABLE IF NOT EXISTS `siroma_db`.`application_documents` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `application_id` BIGINT UNSIGNED NOT NULL,
  `document_type` ENUM('cv', 'portfolio', 'certificate', 'other') NOT NULL DEFAULT 'other',
  `original_file_name` VARCHAR(255) NOT NULL,
  `file_path` VARCHAR(512) NOT NULL,
  `uploaded_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_application_documents_path` (`application_id` ASC, `file_path` ASC) VISIBLE,
  CONSTRAINT `fk_application_documents_application`
    FOREIGN KEY (`application_id`)
    REFERENCES `siroma_db`.`applications` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `siroma_db`.`divisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siroma_db`.`divisions` ;

CREATE TABLE IF NOT EXISTS `siroma_db`.`divisions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT UNSIGNED NOT NULL,
  `division_name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_divisions_organization_name` (`organization_id` ASC, `division_name` ASC) VISIBLE,
  CONSTRAINT `fk_divisions_organization`
    FOREIGN KEY (`organization_id`)
    REFERENCES `siroma_db`.`organizations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `siroma_db`.`application_preferences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siroma_db`.`application_preferences` ;

CREATE TABLE IF NOT EXISTS `siroma_db`.`application_preferences` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `application_id` BIGINT UNSIGNED NOT NULL,
  `division_id` BIGINT UNSIGNED NOT NULL,
  `preference_order` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_application_preferences_division` (`application_id` ASC, `division_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_application_preferences_order` (`application_id` ASC, `preference_order` ASC) VISIBLE,
  INDEX `idx_application_preferences_division_order` (`division_id` ASC, `preference_order` ASC) VISIBLE,
  CONSTRAINT `fk_application_preferences_application`
    FOREIGN KEY (`application_id`)
    REFERENCES `siroma_db`.`applications` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_application_preferences_division`
    FOREIGN KEY (`division_id`)
    REFERENCES `siroma_db`.`divisions` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `siroma_db`.`application_status_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siroma_db`.`application_status_history` ;

CREATE TABLE IF NOT EXISTS `siroma_db`.`application_status_history` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `application_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `application_code` VARCHAR(30) NOT NULL,
  `old_status` VARCHAR(30) NULL DEFAULT NULL,
  `new_status` VARCHAR(30) NOT NULL,
  `change_note` VARCHAR(500) NULL DEFAULT NULL,
  `changed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_application_status_history_app_date` (`application_id` ASC, `changed_at` ASC) VISIBLE,
  CONSTRAINT `fk_application_status_history_application`
    FOREIGN KEY (`application_id`)
    REFERENCES `siroma_db`.`applications` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `siroma_db`.`organization_members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siroma_db`.`organization_members` ;

CREATE TABLE IF NOT EXISTS `siroma_db`.`organization_members` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `member_role` ENUM('chairperson', 'recruitment_admin', 'interviewer', 'member') NOT NULL DEFAULT 'member',
  `joined_at` DATE NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_organization_members` (`organization_id` ASC, `user_id` ASC) VISIBLE,
  INDEX `fk_organization_members_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_organization_members_organization`
    FOREIGN KEY (`organization_id`)
    REFERENCES `siroma_db`.`organizations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_organization_members_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `siroma_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `siroma_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `siroma_db`.`v_application_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siroma_db`.`v_application_details` (`application_id` INT, `application_code` INT, `student_number` INT, `full_name` INT, `email` INT, `organization_code` INT, `organization_name` INT, `recruitment_title` INT, `academic_year` INT, `division_preferences` INT, `total_documents` INT, `final_score` INT, `application_status` INT, `submitted_at` INT);

-- -----------------------------------------------------
-- Placeholder table for view `siroma_db`.`v_division_interest_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siroma_db`.`v_division_interest_summary` (`recruitment_period_id` INT, `recruitment_title` INT, `organization_name` INT, `division_id` INT, `division_name` INT, `total_interested_applicants` INT, `total_first_choice` INT, `total_second_choice` INT);

-- -----------------------------------------------------
-- Placeholder table for view `siroma_db`.`v_recruitment_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siroma_db`.`v_recruitment_summary` (`recruitment_period_id` INT, `organization_name` INT, `recruitment_title` INT, `registration_start_date` INT, `registration_end_date` INT, `total_quota` INT, `recruitment_status` INT, `total_applicants` INT, `total_submitted` INT, `total_under_review` INT, `total_accepted` INT, `total_rejected` INT, `remaining_quota` INT);

-- -----------------------------------------------------
-- procedure sp_delete_application
-- -----------------------------------------------------

USE `siroma_db`;
DROP procedure IF EXISTS `siroma_db`.`sp_delete_application`;

DELIMITER $$
USE `siroma_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_delete_application`(
    IN p_application_id BIGINT UNSIGNED,
    IN p_delete_reason VARCHAR(500)
)
main_block: BEGIN
    DECLARE v_application_count INT DEFAULT 0;
    DECLARE v_application_status VARCHAR(30) DEFAULT NULL;
    DECLARE v_application_code VARCHAR(30) DEFAULT NULL;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    SELECT COUNT(*),
           MAX(application_status),
           MAX(application_code)
    INTO v_application_count,
         v_application_status,
         v_application_code
    FROM applications
    WHERE id = p_application_id;

    IF v_application_count = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Aplikasi yang akan dihapus tidak ditemukan.';
    END IF;

    IF v_application_status NOT IN ('submitted', 'withdrawn') THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Aplikasi hanya dapat dihapus ketika berstatus submitted atau withdrawn.';
    END IF;

    START TRANSACTION;

    INSERT INTO application_status_history (
        application_id,
        application_code,
        old_status,
        new_status,
        change_note
    )
    VALUES (
        p_application_id,
        v_application_code,
        v_application_status,
        'deleted',
        COALESCE(NULLIF(TRIM(p_delete_reason), ''), 'Aplikasi dihapus.')
    );

    DELETE FROM applications
    WHERE id = p_application_id;

    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_get_recruitment_results
-- -----------------------------------------------------

USE `siroma_db`;
DROP procedure IF EXISTS `siroma_db`.`sp_get_recruitment_results`;

DELIMITER $$
USE `siroma_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_get_recruitment_results`(
    IN p_recruitment_period_id BIGINT UNSIGNED,
    IN p_status_filter VARCHAR(20),
    OUT p_total_applicants INT
)
main_block: BEGIN
    DECLARE v_recruitment_count INT DEFAULT 0;

    SELECT COUNT(*)
    INTO v_recruitment_count
    FROM recruitment_periods
    WHERE id = p_recruitment_period_id;

    IF v_recruitment_count = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Periode rekrutmen tidak ditemukan.';
    END IF;

    IF p_status_filter IS NOT NULL
       AND p_status_filter NOT IN (
            'submitted',
            'under_review',
            'accepted',
            'rejected',
            'withdrawn'
       ) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Filter status tidak valid.';
    END IF;

    SELECT COUNT(*)
    INTO p_total_applicants
    FROM applications
    WHERE recruitment_period_id = p_recruitment_period_id
      AND (
          p_status_filter IS NULL
          OR application_status = p_status_filter
      );

    SELECT
        a.application_code,
        u.student_number,
        u.full_name,
        u.study_program,
        GROUP_CONCAT(
            CONCAT(ap.preference_order, '. ', d.division_name)
            ORDER BY ap.preference_order
            SEPARATOR ', '
        ) AS division_preferences,
        a.final_score,
        a.application_status,
        a.submitted_at,
        a.reviewed_at
    FROM applications a
    JOIN users u
        ON u.id = a.user_id
    LEFT JOIN application_preferences ap
        ON ap.application_id = a.id
    LEFT JOIN divisions d
        ON d.id = ap.division_id
    WHERE a.recruitment_period_id = p_recruitment_period_id
      AND (
          p_status_filter IS NULL
          OR a.application_status = p_status_filter
      )
    GROUP BY
        a.id,
        a.application_code,
        u.student_number,
        u.full_name,
        u.study_program,
        a.final_score,
        a.application_status,
        a.submitted_at,
        a.reviewed_at
    ORDER BY
        a.final_score DESC,
        a.submitted_at ASC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_submit_application
-- -----------------------------------------------------

USE `siroma_db`;
DROP procedure IF EXISTS `siroma_db`.`sp_submit_application`;

DELIMITER $$
USE `siroma_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_submit_application`(
    IN p_user_id BIGINT UNSIGNED,
    IN p_recruitment_period_id BIGINT UNSIGNED,
    IN p_first_division_id BIGINT UNSIGNED,
    IN p_second_division_id BIGINT UNSIGNED,
    IN p_motivation TEXT,
    OUT p_application_id BIGINT UNSIGNED
)
main_block: BEGIN
    DECLARE v_user_count INT DEFAULT 0;
    DECLARE v_recruitment_count INT DEFAULT 0;
    DECLARE v_division_count INT DEFAULT 0;
    DECLARE v_duplicate_count INT DEFAULT 0;
    DECLARE v_organization_id BIGINT UNSIGNED DEFAULT NULL;
    DECLARE v_application_code VARCHAR(30) DEFAULT NULL;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET p_application_id = NULL;
        RESIGNAL;
    END;

    SET p_application_id = NULL;

    SELECT COUNT(*)
    INTO v_user_count
    FROM users
    WHERE id = p_user_id
      AND is_active = TRUE;

    IF v_user_count = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'User tidak ditemukan atau akun tidak aktif.';
    END IF;

    SELECT COUNT(*), MAX(organization_id)
    INTO v_recruitment_count, v_organization_id
    FROM recruitment_periods
    WHERE id = p_recruitment_period_id
      AND recruitment_status = 'open'
      AND CURRENT_DATE BETWEEN registration_start_date
                           AND registration_end_date;

    IF v_recruitment_count = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Periode rekrutmen tidak tersedia atau sudah ditutup.';
    END IF;

    IF p_first_division_id IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Pilihan divisi pertama wajib diisi.';
    END IF;

    IF p_motivation IS NULL OR CHAR_LENGTH(TRIM(p_motivation)) < 20 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Motivasi wajib diisi minimal 20 karakter.';
    END IF;

    SELECT COUNT(*)
    INTO v_duplicate_count
    FROM applications
    WHERE recruitment_period_id = p_recruitment_period_id
      AND user_id = p_user_id;

    IF v_duplicate_count > 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'User sudah mendaftar pada periode rekrutmen ini.';
    END IF;

    SELECT COUNT(*)
    INTO v_division_count
    FROM divisions
    WHERE id = p_first_division_id
      AND organization_id = v_organization_id
      AND is_active = TRUE;

    IF v_division_count = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Pilihan divisi pertama tidak valid untuk organisasi tersebut.';
    END IF;

    IF p_second_division_id IS NOT NULL THEN
        IF p_second_division_id = p_first_division_id THEN
            SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'Pilihan divisi kedua harus berbeda dari pilihan pertama.';
        END IF;

        SELECT COUNT(*)
        INTO v_division_count
        FROM divisions
        WHERE id = p_second_division_id
          AND organization_id = v_organization_id
          AND is_active = TRUE;

        IF v_division_count = 0 THEN
            SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'Pilihan divisi kedua tidak valid untuk organisasi tersebut.';
        END IF;
    END IF;

    START TRANSACTION;

    INSERT INTO applications (
        application_code,
        recruitment_period_id,
        user_id,
        motivation,
        application_status
    )
    VALUES (
        '',
        p_recruitment_period_id,
        p_user_id,
        TRIM(p_motivation),
        'submitted'
    );

    SET p_application_id = LAST_INSERT_ID();

    SELECT application_code
    INTO v_application_code
    FROM applications
    WHERE id = p_application_id;

    INSERT INTO application_preferences (
        application_id,
        division_id,
        preference_order
    )
    VALUES (
        p_application_id,
        p_first_division_id,
        1
    );

    IF p_second_division_id IS NOT NULL THEN
        INSERT INTO application_preferences (
            application_id,
            division_id,
            preference_order
        )
        VALUES (
            p_application_id,
            p_second_division_id,
            2
        );
    END IF;

    INSERT INTO application_status_history (
        application_id,
        application_code,
        old_status,
        new_status,
        change_note
    )
    VALUES (
        p_application_id,
        v_application_code,
        NULL,
        'submitted',
        'Aplikasi dibuat melalui sp_submit_application.'
    );

    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_update_application_status
-- -----------------------------------------------------

USE `siroma_db`;
DROP procedure IF EXISTS `siroma_db`.`sp_update_application_status`;

DELIMITER $$
USE `siroma_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_update_application_status`(
    IN p_application_id BIGINT UNSIGNED,
    IN p_new_status VARCHAR(20),
    IN p_final_score DECIMAL(5,2),
    IN p_reviewer_notes VARCHAR(500)
)
main_block: BEGIN
    DECLARE v_application_count INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        SET @application_status_note = NULL;
        ROLLBACK;
        RESIGNAL;
    END;

    IF p_new_status IS NULL
       OR p_new_status NOT IN (
            'submitted',
            'under_review',
            'accepted',
            'rejected',
            'withdrawn'
       ) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Status aplikasi tidak valid.';
    END IF;

    IF p_final_score IS NOT NULL
       AND (p_final_score < 0 OR p_final_score > 100) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Nilai akhir harus berada pada rentang 0 sampai 100.';
    END IF;

    IF p_new_status IN ('accepted', 'rejected')
       AND p_final_score IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Nilai akhir wajib diisi untuk status accepted atau rejected.';
    END IF;

    SELECT COUNT(*)
    INTO v_application_count
    FROM applications
    WHERE id = p_application_id;

    IF v_application_count = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Aplikasi tidak ditemukan.';
    END IF;

    START TRANSACTION;

    SET @application_status_note = NULLIF(TRIM(p_reviewer_notes), '');

    UPDATE applications
    SET application_status = p_new_status,
        final_score = p_final_score,
        reviewer_notes = p_reviewer_notes,
        reviewed_at = CASE
            WHEN p_new_status IN ('under_review', 'accepted', 'rejected')
                THEN CURRENT_TIMESTAMP
            ELSE reviewed_at
        END
    WHERE id = p_application_id;

    SET @application_status_note = NULL;

    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `siroma_db`.`v_application_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siroma_db`.`v_application_details`;
DROP VIEW IF EXISTS `siroma_db`.`v_application_details` ;
USE `siroma_db`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `siroma_db`.`v_application_details` AS select `a`.`id` AS `application_id`,`a`.`application_code` AS `application_code`,`u`.`student_number` AS `student_number`,`u`.`full_name` AS `full_name`,`u`.`email` AS `email`,`o`.`organization_code` AS `organization_code`,`o`.`organization_name` AS `organization_name`,`rp`.`recruitment_title` AS `recruitment_title`,`rp`.`academic_year` AS `academic_year`,group_concat(distinct concat(`ap`.`preference_order`,'. ',`d`.`division_name`) order by `ap`.`preference_order` ASC separator ', ') AS `division_preferences`,count(distinct `ad`.`id`) AS `total_documents`,`a`.`final_score` AS `final_score`,`a`.`application_status` AS `application_status`,`a`.`submitted_at` AS `submitted_at` from ((((((`siroma_db`.`applications` `a` join `siroma_db`.`users` `u` on((`u`.`id` = `a`.`user_id`))) join `siroma_db`.`recruitment_periods` `rp` on((`rp`.`id` = `a`.`recruitment_period_id`))) join `siroma_db`.`organizations` `o` on((`o`.`id` = `rp`.`organization_id`))) left join `siroma_db`.`application_preferences` `ap` on((`ap`.`application_id` = `a`.`id`))) left join `siroma_db`.`divisions` `d` on((`d`.`id` = `ap`.`division_id`))) left join `siroma_db`.`application_documents` `ad` on((`ad`.`application_id` = `a`.`id`))) group by `a`.`id`,`a`.`application_code`,`u`.`student_number`,`u`.`full_name`,`u`.`email`,`o`.`organization_code`,`o`.`organization_name`,`rp`.`recruitment_title`,`rp`.`academic_year`,`a`.`final_score`,`a`.`application_status`,`a`.`submitted_at`;

-- -----------------------------------------------------
-- View `siroma_db`.`v_division_interest_summary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siroma_db`.`v_division_interest_summary`;
DROP VIEW IF EXISTS `siroma_db`.`v_division_interest_summary` ;
USE `siroma_db`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `siroma_db`.`v_division_interest_summary` AS select `rp`.`id` AS `recruitment_period_id`,`rp`.`recruitment_title` AS `recruitment_title`,`o`.`organization_name` AS `organization_name`,`d`.`id` AS `division_id`,`d`.`division_name` AS `division_name`,count(`ap`.`id`) AS `total_interested_applicants`,sum((case when (`ap`.`preference_order` = 1) then 1 else 0 end)) AS `total_first_choice`,sum((case when (`ap`.`preference_order` = 2) then 1 else 0 end)) AS `total_second_choice` from ((((`siroma_db`.`recruitment_periods` `rp` join `siroma_db`.`organizations` `o` on((`o`.`id` = `rp`.`organization_id`))) join `siroma_db`.`divisions` `d` on((`d`.`organization_id` = `rp`.`organization_id`))) left join `siroma_db`.`applications` `a` on((`a`.`recruitment_period_id` = `rp`.`id`))) left join `siroma_db`.`application_preferences` `ap` on(((`ap`.`application_id` = `a`.`id`) and (`ap`.`division_id` = `d`.`id`)))) group by `rp`.`id`,`rp`.`recruitment_title`,`o`.`organization_name`,`d`.`id`,`d`.`division_name`;

-- -----------------------------------------------------
-- View `siroma_db`.`v_recruitment_summary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siroma_db`.`v_recruitment_summary`;
DROP VIEW IF EXISTS `siroma_db`.`v_recruitment_summary` ;
USE `siroma_db`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `siroma_db`.`v_recruitment_summary` AS select `rp`.`id` AS `recruitment_period_id`,`o`.`organization_name` AS `organization_name`,`rp`.`recruitment_title` AS `recruitment_title`,`rp`.`registration_start_date` AS `registration_start_date`,`rp`.`registration_end_date` AS `registration_end_date`,`rp`.`total_quota` AS `total_quota`,`rp`.`recruitment_status` AS `recruitment_status`,count(`a`.`id`) AS `total_applicants`,sum((case when (`a`.`application_status` = 'submitted') then 1 else 0 end)) AS `total_submitted`,sum((case when (`a`.`application_status` = 'under_review') then 1 else 0 end)) AS `total_under_review`,sum((case when (`a`.`application_status` = 'accepted') then 1 else 0 end)) AS `total_accepted`,sum((case when (`a`.`application_status` = 'rejected') then 1 else 0 end)) AS `total_rejected`,greatest((`rp`.`total_quota` - sum((case when (`a`.`application_status` = 'accepted') then 1 else 0 end))),0) AS `remaining_quota` from ((`siroma_db`.`recruitment_periods` `rp` join `siroma_db`.`organizations` `o` on((`o`.`id` = `rp`.`organization_id`))) left join `siroma_db`.`applications` `a` on((`a`.`recruitment_period_id` = `rp`.`id`))) group by `rp`.`id`,`o`.`organization_name`,`rp`.`recruitment_title`,`rp`.`registration_start_date`,`rp`.`registration_end_date`,`rp`.`total_quota`,`rp`.`recruitment_status`;
USE `siroma_db`;

DELIMITER $$

USE `siroma_db`$$
DROP TRIGGER IF EXISTS `siroma_db`.`trg_recruitment_periods_bi_validate_dates` $$
USE `siroma_db`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `siroma_db`.`trg_recruitment_periods_bi_validate_dates`
BEFORE INSERT ON `siroma_db`.`recruitment_periods`
FOR EACH ROW
BEGIN
    IF NEW.registration_end_date < NEW.registration_start_date THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Tanggal penutupan tidak boleh sebelum tanggal pembukaan.';
    END IF;

    IF NEW.total_quota IS NULL OR NEW.total_quota = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Kuota rekrutmen harus lebih dari 0.';
    END IF;
END$$


USE `siroma_db`$$
DROP TRIGGER IF EXISTS `siroma_db`.`trg_applications_au_log_status` $$
USE `siroma_db`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `siroma_db`.`trg_applications_au_log_status`
AFTER UPDATE ON `siroma_db`.`applications`
FOR EACH ROW
BEGIN
    IF NOT (OLD.application_status <=> NEW.application_status) THEN
        INSERT INTO application_status_history (
            application_id,
            application_code,
            old_status,
            new_status,
            change_note
        )
        VALUES (
            NEW.id,
            NEW.application_code,
            OLD.application_status,
            NEW.application_status,
            COALESCE(
                @application_status_note,
                'Status diubah langsung melalui perintah UPDATE.'
            )
        );
    END IF;
END$$


USE `siroma_db`$$
DROP TRIGGER IF EXISTS `siroma_db`.`trg_applications_bi_validate_submission` $$
USE `siroma_db`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `siroma_db`.`trg_applications_bi_validate_submission`
BEFORE INSERT ON `siroma_db`.`applications`
FOR EACH ROW
BEGIN
    DECLARE v_open_period_count INT DEFAULT 0;

    SELECT COUNT(*)
    INTO v_open_period_count
    FROM recruitment_periods rp
    WHERE rp.id = NEW.recruitment_period_id
      AND rp.recruitment_status = 'open'
      AND CURRENT_DATE BETWEEN rp.registration_start_date
                           AND rp.registration_end_date;

    IF v_open_period_count = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Pendaftaran hanya dapat dilakukan pada periode rekrutmen yang sedang dibuka.';
    END IF;

    IF NEW.application_code IS NULL OR TRIM(NEW.application_code) = '' THEN
        SET NEW.application_code = CONCAT(
            'APP-',
            DATE_FORMAT(CURRENT_TIMESTAMP, '%Y%m%d'),
            '-',
            UPPER(SUBSTRING(REPLACE(UUID(), '-', ''), 1, 8))
        );
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
